var ALL_MODULE = {
	'GBOX_SPD_1':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'40001'},
					{'field_name':'40003'},
					{'field_name':'40015'},
					{'field_name':'40017'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'40005'},
					{'field_name':'40007'},
					{'field_name':'40009'},
					{'field_name':'40011'},
					{'field_name':'40013'}
				]
			}
		]
	},
	'GBOX_SPD1_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'40001'},
					{'field_name':'40003'},
					{'field_name':'40015'},
					{'field_name':'40017'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'40005'},
					{'field_name':'40007'},
					{'field_name':'40009'},
					{'field_name':'40011'},
					{'field_name':'40013'}
				]
			}
		]
	},
	'GBOX_SPD1_02':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'50'},
					{'field_name':'49'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'}
				]
			}
		]
	},
	'GBOX_SPD2_01A':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'40001'},
					{'field_name':'40002'},
					{'field_name':'40003'},
					{'field_name':'40004'},
					{'field_name':'40005'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'40009'},
					{'field_name':'40010'},
					{'field_name':'400010'},
					{'field_name':'40011'},
					{'field_name':'400011'},
					{'field_name':'40012'},
					{'field_name':'400012'}
				]
			}
		]
	},
	'GBOX_SPD2_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'40001'},
					{'field_name':'40002'},
					{'field_name':'40003'},
					{'field_name':'40004'},
					{'field_name':'40005'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'40009'},
					{'field_name':'40010'},
					{'field_name':'40011'},
					{'field_name':'40012'},
				]
			}
		]
	},
	'GBOX_SPD_2':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'40001'},
					{'field_name':'40002'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'40005'},
					{'field_name':'40006'},
					{'field_name':'40007'},
					{'field_name':'40008'}
				]
			}
		]
	},
	'GBOX_SPD4_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'16'},
					{'field_name':'17'},
					{'field_name':'18'},
					{'field_name':'19'},
					{'field_name':'20'},
					{'field_name':'24'}
				]
			}
		]
	},
	'GBOX_SPD2_B1_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'49'},
					{'field_name':'50'},
					{'field_name':'51'},
					{'field_name':'52'},
					{'field_name':'53'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'},
					{'field_name':'13'}
				]
			},
			{
				'name':'流量计二',
				'modules':[
					{'field_name':'17'},
					{'field_name':'18'},
					{'field_name':'19'},
					{'field_name':'20'},
					{'field_name':'21'}
				]
			}
		]
	},
	'GBOX_GS_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'3'},
					{'field_name':'7'},
					{'field_name':'9'},
					{'field_name':'41'},
					{'field_name':'11'},
					{'field_name':'13'},
					{'field_name':'61'},
					{'field_name':'59'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'57'},
					{'field_name':'67'}
				]
			}
		]
	},
	'GBOX_GS_A1_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'2'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'8'},
					{'field_name':'6'},
					{'field_name':'7'},
					{'field_name':'10'},
					{'field_name':'11'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'12'}
				]
			}
		]
	},
	'GBOX_GS1_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'3'},
					{'field_name':'7'},
					{'field_name':'9'},
					{'field_name':'11'},
					{'field_name':'13'},
					{'field_name':'59'},
					{'field_name':'61'},
					{'field_name':'69'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'57'},
					{'field_name':'67'}
				]
			}
		]
	},
	'GBOX_GS2_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'3'},
					{'field_name':'7'},
					{'field_name':'9'},
					{'field_name':'11'},
					{'field_name':'23'},
					{'field_name':'25'},
					{'field_name':'59'},
					{'field_name':'61'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'15'},
					{'field_name':'17'},
					{'field_name':'19'},
					{'field_name':'21'}
				]

			}
		]
	},
	'GBOX_GS3_01':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'49'},
					{'field_name':'50'},
					{'field_name':'52'},
					{'field_name':'4'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]

			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'12'}
				]
			}
		]
	},
	'GBOX_SPD_S_T_S_F':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'},
					{'field_name':'13'}
				]
			}
		]
	},
	'GBOX_SPD_M_T_S_F':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'49'},
					{'field_name':'50'},
					{'field_name':'51'},
					{'field_name':'52'},
					{'field_name':'53'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'190'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'},
					{'field_name':'13'}
				]
			}
		]
	},
	'GBOX_SPD_S_T_M_F':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'},
					{'field_name':'13'}
				]
			},
			{
				'name':'流量计二',
				'modules':[
					{'field_name':'17'},
					{'field_name':'18'},
					{'field_name':'19'},
					{'field_name':'20'},
					{'field_name':'21'}
				]
			}
		]
	},
	'GBOX_SPD_M_T_M_F':{
		'tank':[
			{
				'name':'储罐',
				'modules':[
					{'field_name':'1'},
					{'field_name':'2'},
					{'field_name':'3'},
					{'field_name':'4'},
					{'field_name':'5'},
					{'field_name':'49'},
					{'field_name':'50'},
					{'field_name':'51'},
					{'field_name':'52'},
					{'field_name':'53'},
					{'field_name':'57'},
					{'field_name':'58'},
					{'field_name':'59'},
					{'field_name':'60'},
					{'field_name':'61'},
					{'field_name':'184'},
					{'field_name':'185'},
					{'field_name':'186'},
					{'field_name':'187'},
					{'field_name':'188'},
					{'field_name':'189'},
					{'field_name':'191'},
					{'field_name':'192'},
					{'field_name':'193'},
					{'field_name':'194'},
					{'field_name':'195'}
				]
			}
		],
		'flow':[
			{
				'name':'流量计一',
				'modules':[
					{'field_name':'9'},
					{'field_name':'10'},
					{'field_name':'11'},
					{'field_name':'12'},
					{'field_name':'13'}
				]
			},
			{
				'name':'流量计二',
				'modules':[
					{'field_name':'17'},
					{'field_name':'18'},
					{'field_name':'19'},
					{'field_name':'20'},
					{'field_name':'21'}
				]
			}
		]
	},

	'GBOX_GAS_DEWARS':{
		tank:[
			{
				name:'气瓶组',
				modules:[
					{field_name:'3'},
					{field_name:'218'}
				]
			}
		],
		flow:[
			{
				name:'流量计一',
				modules:[
					{field_name:'9'},
					{field_name:'10'},
					{field_name:'11'},
					{field_name:'12'}

				]
			}


		]

	}
};